version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./sql:/Users\Admin\IdeaProjects\Deadline\sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass